on:
  pull_request:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'gnu-agpl-v3.0.md'
      - 'infection.json.dist'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - 'psalm.xml'
      - 'README.md'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'gnu-agpl-v3.0.md'
      - 'infection.json.dist'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - 'psalm.xml'
      - 'README.md'

name: Composer require checker

jobs:
  composer-require-checker:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.2', '8.3', '8.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Check dependencies
        run: vendor/bin/composer-require-checker
