on:
  pull_request:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'gnu-agpl-v3.0.md'
      - 'infection.json.dist'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - 'README.md'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'gnu-agpl-v3.0.md'
      - 'infection.json.dist'
      - 'LICENSE'
      - 'phpunit.xml.dist'
      - 'README.md'

name: static analysis

jobs:
  psalm:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.2', '8.3', '8.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-values: memory_limit=-1
          coverage: xdebug

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Static analysis
        run: vendor/bin/psalm --config=psalm.xml --shepherd --stats --output-format=github --php-version=${{ matrix.php }}
